---
Name: consent-records-routes
After: framework/routes#coreroutes
---
Director:
  rules:
    'consent//$Action': 'Mouseketeers\\ConsentRecords\\CookieConsentConfigurationController'
    'cookie-consent//$Action': 'Mouseketeers\\ConsentRecords\\CookieConsentConfigurationController'